
[workspace]
members = ["task_1", "task_10", "task_11", "task_12", "task_13", "task_14", "task_15", "task_16", "task_17", "task_18", "task_19","task_2", "task_3", "task_4", "task_4", "task_5", "task_6", "task_7", "task_8", "task_9"]
resolver = "2"
